### ISSUE TITLE
Effect size comparison

### ISSUE THREAD

**Issue by ballarinit** [arcaldwell49/SuperpowerBook#6]
Hi, thank you for fixing the GPower screenshot in section 5.1. 
I see that the effect size in GPower is now set to "as in spss" from the possible options. 
Could you explain the difference between the f given by default and the f(U), and how this fit with the superpower effect size definition? 
I think the second example in the same book section should be fixed too. 
Thank you

**Comment by arcaldwell49** [comment]
I will look into it. 

Regarding the differences, please read the paper (specifically Box 2) associated with the package as well as the documentation for Gpower.

https://doi.org/10.1177%2F2515245920951503
